@startuml
left to right direction
skinparam usecase {
  BackgroundColor<<Critical>> LightSalmon
  ArrowColor DarkBlue
  FontSize 12
}

actor Root <<System/Server Administrator>>

package "Household Setup" {
  (Create Household) as UC_CreateHousehold <<Critical>>
  (Create Initial Admin Account) as UC_CreateAdminAccount <<Critical>>
  (Send Invitation to Administrator) as UC_SendInvitation <<Critical>>
  (Remove Household) as UC_RemoveHousehold <<Critical>>

  Root --> UC_CreateHousehold
  Root --> UC_CreateAdminAccount
  Root --> UC_SendInvitation
  Root --> UC_RemoveHousehold
}
@enduml

@startuml
left to right direction
skinparam usecase {
  BackgroundColor<<Critical>> LightSalmon
  ArrowColor DarkBlue
  FontSize 12
}

actor Administrator <<Household Manager>>
actor User <<Household Member>>


package "Account Operations" {
  (Register Account) as UC_Register
  (Login) as UC_Login <<Critical>>
  (Logout) as UC_Logout
  (Change Credentials) as UC_ChangeCredentials
  (Reset Password) as UC_ResetPassword <<Optional>>

  (Verify Household Membership) as UC_VerifyHousehold <<include>>
  UC_Register --> UC_VerifyHousehold

  User --> UC_Register
  User --> UC_Login
  User --> UC_Logout
  User --> UC_ChangeCredentials
  User --> UC_ResetPassword

  Administrator --> UC_Login
  Administrator --> UC_Logout
  Administrator --> UC_ChangeCredentials
  Administrator --> UC_ResetPassword
}

package "Household Administration" {
  (Change Household Name) as UC_ChangeHouseholdName
  (Invite New Member) as UC_InviteMember
  (Remove Member) as UC_RemoveMember
  (Assign Administrator Role) as UC_AssignAdminRole
  (View Household Members) as UC_ViewHouseholdMembers

  Administrator --> UC_ChangeHouseholdName
  Administrator --> UC_InviteMember
  Administrator --> UC_RemoveMember
  Administrator --> UC_AssignAdminRole
  Administrator --> UC_ViewHouseholdMembers

  User --> UC_ViewHouseholdMembers
}

(Show Error Message) as UC_ShowErrorMessage <<Critical>>
UC_Login ..> UC_ShowErrorMessage : <<extend>>
note right of UC_ShowErrorMessage
  Triggered when wrong credentials are provided.
end note

@enduml