@startuml
actor "New User" as AppUser
participant "Frontend (React)" as FE
participant "/signup route\n (Flask Blueprint)" as SR
participant "UserService" as US
participant "EmailVerificationService" as ES
participant "User Model Object \n (SQLAlchemy\n to Database)" as UM
participant "External \n Email Service" as Mail

== Sign up Process (User story #23) ==
AppUser -> FE : Navigates to sign up form
activate FE
AppUser <-- FE : Sign up form
AppUser -> FE : Fills sign up form {email, plain_password} and submits
FE -> SR : HTTP Request: POST {email, plain_password}
deactivate FE
activate SR
SR -> ES : is_email_format_valid(email)
activate ES
alt Email format not valid
    SR <-- ES : False
    FE <-- SR : HTTP Response: 400 Bad Request (Email format not valid)
    activate FE
    AppUser <-- FE : Error: Email format not valid, try again
    deactivate FE
end
SR <-- ES : True
deactivate ES
SR -> US : query_users_by_mail(email)
activate US
alt Account already exists
    SR <-- US : User (object)
    FE <-- SR : HTTP Response: 409 Conflict (User exists)
    activate FE
    AppUser <-- FE : Error: account already exists, redirects to login page
    deactivate FE
end
SR <-- US : None
deactivate US
SR -> ES : create_verification_token()
activate ES
SR <-- ES : verification_token
deactivate ES
SR -> US : create_user(unverified_email, plain_password, plain_verification_token)
activate US
US -> UM : new(unverified_email, plain_password, plain_verification_token)
activate UM
UM -> UM : __hash_secret(password)
activate UM
deactivate UM
UM -> UM : __hash_secret(plain_verification_token)
activate UM
deactivate UM
UM -> UM : verification_exp_at = (now + 48h)
activate UM
deactivate UM
US <-- UM : User (object)
deactivate UM
SR <-- US : User (object)
deactivate US
SR -> ES : send_verification_mail(verification_token, unverified_email)
activate ES
ES -> ES : __create_verification_link(plain_verification_token, unverified_email)
activate ES
deactivate ES
ES -> Mail : send email {verification_link, email}
activate Mail
SR <-- ES : User (object)
deactivate ES
deactivate ES
FE <-- SR : HTTP Response: 201 Created (User created)
deactivate SR
activate FE
AppUser <-- FE : Success Message and "check your mail"
deactivate FE
AppUser <- Mail : Mail with link
deactivate Mail
@enduml