@startuml LoginSequence
actor "User" as User
participant "Frontend (React)" as FE
participant "/api/v1/auth/login route\n(Flask Blueprint)" as ALiR
participant "EmailVerificationService" as ES
participant "AuthService" as AS
participant "UserService" as US
participant "User Model Object\n(SQLAlchemy to Database)" as UM

== Login Process (User Story #25) ==
User -> FE: Submits login credentials
activate FE
FE -> ALiR : HTTP Request: POST {email, plain_password, [user_agent, ip_address]}
deactivate FE
activate ALiR
ALiR -> ES : is_email_format_valid(email)
activate ES
alt
alt Email format not valid
    ALiR <-- ES : False
    FE <-- ALiR : HTTP Response: 404 Not Found
    activate FE
    User <-- FE : Error: credentials not valid
    deactivate FE
end
ALiR <-- ES : True
deactivate ES
ALiR -> US : query_users_by_mail(email)
activate US
alt Unverified Mail does not exist or expired
    ALiR <-- US : None
    FE <-- ALiR : HTTP Response: 404 Not Found
    activate FE
    User <-- FE : Error: credentials not valid
    deactivate FE
end
ALiR <-- US : User object
deactivate US
ALiR -> AS : verify_password(user, plain_password)
activate AS
AS -> UM : verify_password(plain_password)
activate UM
UM -> UM : __hash_secret(plain_password)
activate UM
deactivate UM
alt Password does not match
    AS <-- UM : False
    ALiR <-- AS : False
    FE <-- ALiR : HTTP Response: 404 Not Found
    activate FE
    User <-- FE : Error: credentials not valid
    deactivate FE
end
AS <-- UM : True
deactivate UM
ALiR <-- AS : True
deactivate AS
note right of ALiR : Create JWT: see sep. generic diagram.
FE <-- ALiR : HTTP Response: 200 OK {access_jwt, refresh_jwt}
deactivate ALiR
activate FE
FE -> FE : store access_jwt and refresh_jwt in HTTP only cookie
User <-- FE : Success: Login
deactivate FE
@enduml