@startuml LogoutSequence
actor "User" as User
participant "Frontend (React)" as FE
participant "/api/v1/auth/logout route\n(Flask Blueprint)" as ALoR

== Logout Process (User Story #26) ==
User -> FE : Clicks logout button
activate FE
FE -> ALoR : HTTP Request: POST {access_jwt, [user_agent, ip_address]}
deactivate FE
activate ALoR
note right of ALoR : Revoke JWT: see sep. generic diagram
FE <-- ALoR : HTTP Response: 200 OK
deactivate ALoR
activate FE
User <-- FE : Success, redirects to login page
deactivate FE
@enduml