@startuml EmailVerificationSequence
actor "User" as User
participant "Frontend (React)" as FE
participant "/api/v1/auth/verify route\n (Flask Blueprint)" as AVR
participant "UserService" as US
participant "EmailVerificationService" as ES
participant "User Model Object \n (SQLAlchemy\n to Database)" as UM

== E-Mail Verification (User stories #23, #27) ==
User -> FE : clicks link (send email and token)
activate FE
FE -> AVR : HTTP Request: GET {email, plain_verification_token}
deactivate FE
activate AVR
AVR -> ES : is_email_format_valid(email)
activate ES
alt Email format not valid
    AVR <-- ES : False
    FE <-- AVR : HTTP Response: 404 Not Found
    activate FE
    User <-- FE : Error: link not valid
    deactivate FE
end
AVR <-- ES : True
deactivate ES
AVR -> US : query_users_by_unverified_mail_and_not_expired_verification(unverified_email: str)
activate US
alt Unverified Mail does not exist or expired
    AVR <-- US : None
    FE <-- AVR : HTTP Response: 404 Not Found
    activate FE
    User <-- FE : Error: link not valid
    deactivate FE
end
AVR <-- US : User object
deactivate US
AVR -> ES : verify_email(User, plain_verification_token)
activate ES
ES -> UM : verify_verification_token(plain_verification_token)
activate UM
UM -> UM : __hash_secret(plain_verification_token)
activate UM
deactivate UM
alt verification token does not match
    ES <-- UM : False
    AVR <-- ES : False
    FE <-- AVR : HTTP Response: 404 Not Found
    activate FE
    User <-- FE : Error: link not valid
    deactivate FE
end
ES <-- UM : True
ES -> UM : is_user_verified = True
ES -> UM : email = unverified_email
ES -> UM : unverified_email = ""
deactivate UM
AVR <-- ES : True
deactivate ES
FE <-- AVR : HTTP Response: 200 OK (Email verified)
deactivate AVR
activate FE
User <-- FE : Success Message and redirects to login page
deactivate FE
@enduml
