@startuml ResetPasswordRequestSequence
actor "User" as User
participant "Frontend (React)" as FE
participant "/reset_password/request route\n(Flask Blueprint)" as RRR
participant "UserService" as US
participant "EmailVerificationService" as ES
participant "AuthService" as AS
participant "User Model Object \n (SQLAlchemy\n to Database)" as UM
participant "External \n Email Service" as Mail

== Reset Password Request Process (User story #28) ==
User -> FE : Navigates to reset password form
activate FE
User <-- FE : Reset password form
deactivate FE
User -> FE : Fills reset password form\n{email} and submits
activate FE
FE -> RRR : HTTP Request: POST {email}
deactivate FE
activate RRR
RRR -> ES : is_email_format_valid(email)
activate ES
alt Email format not valid
    RRR <-- ES : False
    FE <-- RRR : HTTP Response: 400 Bad Request (Email format not valid)
    activate FE
    User <-- FE : Error: Email format not valid, try again
    deactivate FE
end
RRR <-- ES : True
deactivate ES
RRR -> US : query_users_by_mail(email)
activate US
alt Account does not exist
    RRR <-- US : None
    FE <-- RRR : HTTP Response: 404 Not Found (User does not exist)
    activate FE
    User <-- FE : Error: account does not exist, try again
    deactivate FE
end
RRR <-- US : User (object)
deactivate US
RRR -> AS : create_reset_password_jwt(User)
activate AS
AS -> AS : __encode_jwt(reset_password_jwt)
activate AS
deactivate AS
AS -> UM : update_reset_password_jwt(reset_password_jwt)
activate UM
UM -> UM : __hash_secret(reset_password_jwt)
activate UM
deactivate UM
deactivate UM
RRR <-- AS : encoded_reset_password_jwt
deactivate AS
RRR -> AS : send_reset_password_email(email, encoded_reset_password_jwt)
activate AS
AS -> AS : __create_reset_password_link(encoded_reset_password_jwt)
activate AS
AS -> Mail : send_email(email, reset_password_link)
activate Mail
deactivate AS
deactivate AS
FE <-- RRR : HTTP Response: 200 OK (Reset password email sent)
deactivate RRR
activate FE
User <-- FE : Success: Reset password email sent
deactivate FE
deactivate RRR
User <- Mail : Email: Reset password link
deactivate Mail
@enduml