@startuml ResetPasswordRequestSequence
actor "User" as User
participant "Frontend (React)" as FE
participant "/api/v1/auth/reset route\n(Flask Blueprint)" as ARsR
participant "UserService" as US
participant "EmailVerificationService" as ES
participant "AuthService" as AS
participant "User Model Object \n (SQLAlchemy\n to Database)" as UM
participant "External \n Email Service" as Mail

== Reset Password Request Process (User story #28) ==
User -> FE : Navigates to reset password form
activate FE
User <-- FE : Reset password form
deactivate FE
User -> FE : Fills reset password form\n{email} and submits
activate FE
FE -> ARsR : HTTP Request: POST {email}
deactivate FE
activate ARsR
ARsR -> ES : is_email_format_valid(email)
activate ES
alt Email format not valid
    ARsR <-- ES : False
    FE <-- ARsR : HTTP Response: 400 Bad Request (Email format not valid)
    activate FE
    User <-- FE : Error: Email format not valid, try again
    deactivate FE
end
ARsR <-- ES : True
deactivate ES
ARsR -> US : query_users_by_mail(email)
activate US
alt Account does not exist
    ARsR <-- US : None
    FE <-- ARsR : HTTP Response: 404 Not Found (User does not exist)
    activate FE
    User <-- FE : Error: account does not exist, try again
    deactivate FE
end
ARsR <-- US : User (object)
deactivate US
ARsR -> AS : create_reset_password_jwt(User)
activate AS
AS -> AS : __encode_jwt(reset_password_jwt)
activate AS
deactivate AS
AS -> UM : update_reset_password_jwt(reset_password_jwt)
activate UM
UM -> UM : __hash_secret(reset_password_jwt)
activate UM
deactivate UM
deactivate UM
ARsR <-- AS : encoded_reset_password_jwt
deactivate AS
ARsR -> AS : send_reset_password_email(email, encoded_reset_password_jwt)
activate AS
AS -> AS : __create_reset_password_link(encoded_reset_password_jwt)
activate AS
AS -> Mail : send_email(email, reset_password_link)
activate Mail
deactivate AS
deactivate AS
FE <-- ARsR : HTTP Response: 200 OK (Reset password email sent)
deactivate ARsR
activate FE
User <-- FE : Success: Reset password email sent
deactivate FE
deactivate ARsR
User <- Mail : Email: Reset password link
deactivate Mail
@enduml