@startuml ResetPasswordConfirmSequence
actor "User" as User
participant "Frontend (React)" as FE
participant "/reset_password/confirm route\n(Flask Blueprint)" as RCR
participant "AuthService" as AS
participant "UserService" as US
participant "User Model Object \n(SQLAlchemy\n to Database)" as UM

== Reset Password Confirm Process (User story #29) ==
User -> FE : Clicks reset password link (with encoded_reset_password_jwt)
activate FE
FE -> RCR : HTTP Request: GET {encoded_reset_password_jwt}
deactivate FE
activate RCR
RCR -> AS : verify_reset_password_jwt(encoded_reset_password_jwt)
activate AS
AS -> AS : __decode_jwt(encoded_reset_password_jwt)
activate AS
alt Decoding reset password JWT fails
    AS <-- AS : None
    RCR <-- AS : None
    FE <-- RCR : HTTP Response: 400 Bad Request (Invalid JWT)
    User <-- FE : Error: Invalid Link
end
AS <-- AS : decoded_reset_password_jwt
deactivate AS
AS -> AS : __is_reset_password_jwt(decoded_reset_password_jwt)
activate AS
alt Token is not a reset password JWT
    AS <-- AS : False
    RCR <-- AS : None
    FE <-- RCR : HTTP Response: 400 Bad Request (Invalid JWT)
    User <-- FE : Error: Invalid Link
end
AS <-- AS : True
deactivate AS
AS -> AS : __has_jwt_expired(decoded_reset_password_jwt)
activate AS
alt Reset password JWT has expired
    AS <-- AS : True
    RCR <-- AS : raise JWTExpiredError("JWT has expired")
    FE <-- RCR : HTTP Response: 400 Bad Request (JWT expired)
    User <-- FE : Error: Link has expired
end
AS <-- AS : False
deactivate AS
AS -> US : query_users_by_id(decoded_reset_password_jwt.sub)
activate US
alt User does not exist
    AS <-- US : None
    RCR <-- AS : None
    FE <-- RCR : HTTP Response: 400 Bas Request (Invalid JWT)
    User <-- FE : Error: Invalid Link
end
AS <-- US : User object
deactivate US
AS -> UM : verify_reset_password_jwt(decoded_reset_password_jwt)
activate UM
UM -> UM : __hash_secret(decoded_reset_password_jwt)
activate UM
deactivate UM
alt JWT does not match User.__hashed_reset_password_jwt
    AS <-- UM : False
    RCR <-- AS : None
    FE <-- RCR : HTTP Response: 400 Bad Request (Invalid JWT)
    User <-- FE : Error: Invalid Link
end
UM <-- UM : Set User.__hashed_reset_password_jwt = None
AS <-- UM : True
deactivate UM
RCR <-- AS : User object
deactivate AS
note right of RCR : Create JWT: see sep. generic diagram.
FE <-- RCR : HTTP Response: 200 OK {access_jwt, refresh_jwt}
deactivate RCR
activate FE
FE -> FE : store access_jwt and refresh_jwt in HTTP only cookie
User <-- FE : Success: redirects to update account form
note right of User : Update account: see sep. diagram.
deactivate FE
@enduml