@startuml ResetPasswordSequence
actor "User" as User
participant "Frontend (React)" as FE
participant "/reset route\n (Flask Blueprint)" as RR
participant "UserService" as US
participant "EmailVerificationService" as ES
participant "AuthService" as AS
participant "User Model Object \n (SQLAlchemy\n to Database)" as UM
participant "External \n Email Service" as Mail

== Reset Password Process (User story #28) ==
User -> FE : Navigates to reset password form
activate FE
User <-- FE : Reset password form
deactivate FE
User -> FE : Fills reset password form\n{email} and submits
activate FE
FE -> RR : HTTP Request: POST {email}
deactivate FE
activate RR
RR -> ES : is_email_format_valid(email)
activate ES
alt Email format not valid
    RR <-- ES : False
    FE <-- RR : HTTP Response: 400 Bad Request (Email format not valid)
    activate FE
    User <-- FE : Error: Email format not valid, try again
    deactivate FE
end
RR <-- ES : True
deactivate ES
RR -> US : query_users_by_mail(email)
activate US
alt Account does not exist
    RR <-- US : None
    FE <-- RR : HTTP Response: 404 Not Found (User does not exist)
    activate FE
    User <-- FE : Error: account does not exist, try again
    deactivate FE
end
RR <-- US : User (object)
deactivate US
RR -> AS : create_reset_password_jwt(User)
activate AS
AS -> AS : __encode_jwt(reset_password_jwt)
activate AS
deactivate AS
AS -> UM : update_reset_password_jwt(reset_password_jwt)
activate UM
UM -> UM : __hash_secret(reset_password_jwt)
activate UM
deactivate UM
deactivate UM
RR <-- AS : encoded_reset_password_jwt
deactivate AS
RR -> AS : send_reset_password_email(email, encoded_reset_password_jwt)
activate AS
AS -> AS : __create_reset_password_link(encoded_reset_password_jwt)
activate AS
AS -> Mail : send_email(email, reset_password_link)
activate Mail
deactivate AS
deactivate AS
FE <-- RR : HTTP Response: 200 OK (Reset password email sent)
deactivate RR
activate FE
User <-- FE : Success: Reset password email sent
deactivate FE
deactivate RR
User <- Mail : Email: Reset password link
deactivate Mail
@enduml