@startuml SignUpSequence
actor "User" as User
participant "Frontend (React)" as FE
participant "/api/v1/auth/sign-up route\n (Flask Blueprint)" as ASR
participant "UserService" as US
participant "EmailVerificationService" as ES
participant "AuthService" as AS
participant "User Model Object \n (SQLAlchemy\n to Database)" as UM
participant "External \n Email Service" as Mail

== Sign up Process (User story #23) ==
User -> FE : Navigates to sign up form
activate FE
User <-- FE : Sign up form
deactivate FE
User -> FE : Fills sign up form\n{email, plain_password, plain_password_confirm} and submits
activate FE
FE -> FE : verify_passwords_match(plain_password, plain_password_confirm)
activate FE
alt Passwords do not match
    FE <-- FE : False
    User <-- FE : Error: Passwords do not match, try again
end
FE <-- FE : True
deactivate FE
FE -> ASR : HTTP Request: POST {email, plain_password}
deactivate FE
activate ASR
ASR -> ES : is_email_format_valid(email)
activate ES
alt Email format not valid
    ASR <-- ES : False
    FE <-- ASR : HTTP Response: 400 Bad Request (Email format not valid)
    activate FE
    User <-- FE : Error: Email format not valid, try again
    deactivate FE
end
ASR <-- ES : True
deactivate ES
ASR -> US : query_users_by_mail(email)
activate US
alt Account already exists
    ASR <-- US : User (object)
    FE <-- ASR : HTTP Response: 409 Conflict (User exists)
    activate FE
    User <-- FE : Error: account already exists, redirects to login page
    deactivate FE
end
ASR <-- US : None
deactivate US
ASR -> AS : does_password_fulfill_requirements(plain_password)
activate AS
alt Password does not fulfill requirements
    ASR <-- AS : False
    FE <-- ASR : HTTP Response: 400 Bad Request (Password requirements not met)
    activate FE
    User <-- FE : Error: Password requirements not met, try again
    deactivate FE
end
ASR <-- AS : True
deactivate AS
ASR -> ES : create_verification_token()
activate ES
ASR <-- ES : verification_token
deactivate ES
ASR -> US : create_user(unverified_email, plain_password, plain_verification_token)
activate US
US -> UM : new(unverified_email, plain_password, plain_verification_token)
activate UM
UM -> UM : __hash_secret(password)
activate UM
deactivate UM
UM -> UM : __hash_secret(plain_verification_token)
activate UM
deactivate UM
UM -> UM : verification_exp_at = (now + 48h)
activate UM
deactivate UM
US <-- UM : User (object)
deactivate UM
ASR <-- US : User (object)
deactivate US
ASR -> ES : send_verification_mail(verification_token, unverified_email)
activate ES
ES -> ES : __create_verification_link(plain_verification_token, unverified_email)
activate ES
deactivate ES
ES -> Mail : send email {verification_link, email}
activate Mail
ASR <-- ES : User (object)
deactivate ES
deactivate ES
FE <-- ASR : HTTP Response: 201 Created (User created)
deactivate ASR
activate FE
User <-- FE : Success Message and "check your mail"
deactivate FE
User <- Mail : Mail with link
deactivate Mail
@enduml