@startuml UpdateAccountSequence
actor "User" as User
participant "Frontend (React)" as FE
participant "/api/v1/accounts route\n(Flask Blueprint)" as AR
participant "UserService" as US
participant "AuthService" as AS
participant "EmailVerificationService" as ES
participant "User Model Object\n(SQLAlchemy to Database)" as UM
participant "External \n Email Service" as Mail

== Update Account Process ==
User -> FE: Navigates to update account form
activate FE
FE -> AR: HTTP Request: GET {access_jwt}
deactivate FE
activate AR
note right of AR: Verify JWT: see sep. generic diagram.
AR -> US: query_users_by_id(decoded_access_jwt.sub)
activate US
AR <-- US: User object
deactivate US
FE <-- AR: HTTP Response: 200 OK {email}
deactivate AR
activate FE
User <-- FE: Update account form\nwith prefilled email and\nempty password fields\n(1 x old, 2 x new)
deactivate FE
User -> FE: Submits update account form
activate FE
FE -> FE: verify_passwords_match(plain_new_password, plain_new_password_confirm)
activate FE
alt Passwords do not match
    FE <-- FE : False
    User <-- FE : Error: Passwords do not match, try again
end
FE <-- FE : True
deactivate FE
FE -> AR: HTTP Request: PATCH {access_jwt, new_email, plain_old_password, plain_new_password}
deactivate FE
activate AR
note right of AR: Verify JWT: see sep. generic diagram.
alt New email was provided
    AR -> ES : is_email_format_valid(new_email)
    activate ES
    alt Email format not valid
        AR <-- ES : False
        FE <-- AR : HTTP Response: 400 Bad Request (Email format not valid)
        activate FE
        User <-- FE : Error: Email format not valid, try again
        deactivate FE
    end
    AR <-- ES : True
    deactivate ES
end
alt New password was provided
    AR -> AS : does_password_fulfill_requirements(plain_new_password)
    activate AS
    alt Password does not fulfill requirements
        AR <-- AS : False
        FE <-- AR : HTTP Response: 400 Bad Request (Password requirements not met)
        activate FE
        User <-- FE : Error: Password requirements not met, try again
        deactivate FE
    end
    AR <-- AS : True
    deactivate AS
    AR -> US : query_users_by_id(decoded_access_jwt.sub)
    activate US
    AR <-- US : User object
    deactivate US
    AR -> AS : verify_password(User, plain_old_password)
    activate AS
    AS -> UM : verify_password(plain_old_password)
    activate UM
    UM -> UM : __hash_secret(plain_old_password)
    activate UM
    deactivate UM
    alt Password does not match
        AS <-- UM : False
        AR <-- AS : False
        FE <-- AR : HTTP Response: 401 Unauthorized
        activate FE
        User <-- FE : Error: Password incorrect, try again
        deactivate FE
    end
    AS <-- UM : True
    deactivate UM
    AR <-- AS : True
    deactivate AS
end
alt New email was provided
    AR -> ES : create_verification_token()
    activate ES
    AR <-- ES : plain_verification_token
    deactivate ES
    AR -> US : query_users_by_id(decoded_access_jwt.sub)
    activate US
    AR <-- US : User object
    deactivate US
    AR -> US : update_user_email(User, new_email, plain_verification_token)
    activate US
    US -> UM : update_email(new_email, plain_verification_token)
    activate UM
    UM -> UM : unverified_email = new_email
    activate UM
    deactivate UM
    UM -> UM : __hash_secret(plain_verification_token)
    activate UM
    deactivate UM
    UM -> UM : verification_exp_at = (now + 48h)
    activate UM
    deactivate UM
    deactivate UM
    deactivate US
    AR -> ES : send_verification_mail(verification_token, unverified_email)
    activate ES
    ES -> ES : __create_verification_link(plain_verification_token, unverified_email)
    activate ES
    deactivate ES
    ES -> Mail : send email {verification_link, email}
    activate Mail
    deactivate ES
    User <- Mail : Mail with link
    deactivate Mail
end
alt New password was provided
    AR -> US : update_user_password(User, plain_new_password)
    activate US
    US -> UM : update_password(plain_new_password)
    activate UM
    UM -> UM : __hash_secret(plain_new_password)
    activate UM
    deactivate UM
    deactivate UM
    deactivate US
end
FE <-- AR: HTTP Response: 200 OK
deactivate AR
activate FE
User <-- FE: Success Message
deactivate FE
@enduml
